line-length = 80
indent-width = 4


[lint]
extend-select = ["I", "E4", "E7", "E9", "F"]

[lint.per-file-ignores]
"app/routes/__init__.py" = ["E402"]

[format]
quote-style = "double" # single
indent-style = "space"
docstring-code-format = true
